# Account info: write the username of all your accounts
account_username:
  - ${{ secrets.USER1 }}
  - ${{ secrets.USER2 }}

# Account info: write the password of all your accounts
account_password:
  - ${{ secrets.PASS1 }}
  - ${{ secrets.PASS2 }}

# Words to search for giveaway
words_to_search:
  - "giveaway"
  - "#giveaway"
  - 'retweet to win'
  - '#retweettowin'
  - "#ContestGame"
  - "ContestGame"
  - "offer follow winner"
  - "contest to win"
  - "win rt"
  - "Win rt + follow"
  - "RT & follow"
  - "rt follow"
  - "contest rt like"
  - "contest rt fav"
  - "RT tweet Follow"
  - "contest rt follow"
  - "rt follow bag"
  - "rt follow draw"
  - "rt follow win"
  - "rt follow comment"
  - "rt follow contest"
  - "rt follow giveaway"
  - "rt follow draw"
  - "rt follow bag"
  - "win contest"
  - "win rt"
  - "contest draw the"
  - "contest results the rt"
  - "draw contest"
  - "contest result the rt"

# Those are the word needed on the tweet for the bot to comment but we won't lookup for a random comment to copy for those words:
word_list_to_not_check_for_copy:
  - "+ #"
  - "with #"
  - "the #"

# Those are the word needed on the tweet for the bot to comment when the tweet ask to comment one thing in particular
word_list_to_check_for_special_comment:
  - "comment with"
  - "comment"
  - "write"
  - "say"
  - "answer"

# Those are the word needed on the tweet for the bot to comment when the tweet ask to comment random stuff
word_list_to_check_for_comment:
  - "+ #"
  - "with #"
  - "the #"
  - "mention #"
  - "comment"
  - "commenting"
  - "write"
  - "say"
  - "mention"
  - "give"
  - "tweet with"
  - "tweeting: with"
  - "tweet: with"
  - "tweet #"
  - "hashtag"
  - "reply"
  - "indicate"

# The same as word_list_to_check_for_comment but for word shorter than 6 characters
short_word_list_to_check_for_comment:
  - "said"
  - "say"

# Those are the word needed on the tweet for the bot to tag one or more account
word_list_to_check_for_tag:
  - "invite"
  - "mention"
  - "tag"
  - "#tag"
  - "identify"
  - "@ one"
  - "@ a"
  - "@ some"
  - "@ your"
  - "@ 1"
  - "@ two"
  - "@ 2"
  - "@ multiple"

# Word list to check if we need to tag 1 account
one_poeple_list:
  - "#contest"
  - "contest"
  - "#ContestGame"
  - "ContestGame"
  - "offer follow winner"
  - "contest to win"
  - "win rt"
  - "Win rt + follow"
  - "RT & follow"
  - "rt follow"
  - "contest rt like"
  - "contest rt fav"
  - "RT tweet Follow"
  - "contest rt follow"
  - "rt follow tas"
  - "rt follow draw"
  - "rt follow win"
  - "rt follow comment"
  - "rt follow contest"
  - "rt follow contest"
  - "rt follow draw"
  - "rt follow tas"
  - "contest to win"
  - "win rt"
  - "contest tas le"
  - "contest results le rt"
  - "draw contest"
  - "contest result le rt"
  - "with #"
  - "the #"
  - "comment with"
  - "comment with"
  - "comment with"
  - "comment with"
  - "comment"
  - "comment"
  - "write"
  - "write"
  - "say"
  - "answer"
  - "answer"
  - "comment with"
  - "comment with"
  - "comment with"
  - "comment with"
  - "comment"
  - "comment"
  - "write"
  - "write"
  - "say"
  - "answer"
  - "answer"
  - "+ #"
  - "with #"
  - "the #"
  - "mention #"
  - "comment"
  - "comment"
  - "commenting"
  - "write"
  - "write"
  - "say"
  - "quote"
  - "give"
  - "tweet with"
  - "tweet with"
  - "tweet with"
  - "tweet with"
  - "tweet #"
  - "hashtag"
  - "answer"
  - "indicate"
  - "say"
  - "say"
  - "com"
  - "invite"
  - "mention"
  - "tag"
  - "#tag"
  - "identify"
  - "@ one"
  - "@ a"
  - "@ some"
  - "@ your"
  - "@ 1"
  - "@ two"
  - "@ 2"
  - "@ multiple"
  - "@ one"
  - "@ 1"
  - "tag one"
  - "tag 1"
  - "tag your"
  - "tag your"
  - "tag your"
  - "tag the"
  - "a friend"
  - "a buddy"
  - "a person"
  - "the person"
  - "a friend"
  - "1 friend"
  - "1 friend"
  - "1 buddy"
  - "1 person"
  - "a friend"
  - "a friend"
  - "someone"
  - "a fan"
  - "1 fan"
  - "a friend"
  - "a friend"

# Word list to check if we need to tag 2 accounts
two_poeple_list:
  - "tag two"
  - "tag 2"
  - "@ two"
  - "@ 2"
  - "2 friends"
  - "2 friends"
  - "2 friends"
  - "2 people"
  - "2 buddies"
  - "2 friends"
  - "2 friends"
  - "2 friends"
  - "2 people"
  - "2 buddies"

# Word list to check if we need to tag 3 accounts or more
three_or_more_poeple_list:
  - "3 friends"
  - "3 friends"
  - "3 friends"
  - "3 people"
  - "3 buddies"
  - "3 friends"
  - "3 friends"
  - "3 friends"
  - "3 people"
  - "3 buddies"
  - "your friends"
  - "some friends"
  - "your buddies"
  - "some buddies"

# Accounts we want to invite you must but a space at the end of each account and a space at the	start of the first account
accounts_to_tag:
  - "@boturitter"
  - "@nasobot"
  - "@botoronga"

# Accounts that we don't want to follow
accounts_to_blacklist:
  - "@RealB0tSpotter"
  - "@jflessauSpam"
  - "@b0ttem"
  - "@BotSpotterBot"
  - "@gulzaarAvi"
  - "@BotFett"
  - "@ElChap0420"
  - "@RealB0tSpotter"
  - "@YNTF"
  - "@0xCryptax"
  - "@0xHaz666"
  - "@0xMakeMoney"
  - "@AGoldboxDeals"
  - "@BestConcourss"
  - "@BlackPromos"
  - "@BrownConcours"
  - "@buuuffNFT"
  - "@ChrisGeekWorld"
  - "@ConcoursYoko"
  - "@Croissant_NFA"
  - "@cryptogmznft"
  - "@destyy657"
  - "@drakebil22"
  - "@Eks74326603"
  - "@FailsDrole"
  - "@oxyGiveaway"
  - "@GarwyNFT"
  - "@GreyConcours"
  - "@LAGAMINGROOM"
  - "@levraizarkx"
  - "@lofi_feeling"
  - "@MkNFTz"
  - "@MONSIEURCHOUYTB"
  - "@MONSIEURCHOYTB"
  - "@NeyaGiveaway"
  - "@nftconcours"
  - "@simmessier"
  - "@NigmoInft"
  - "@Nigmolnft"
  - "@PolinskiNFT"
  - "@slconcours"
  - "@SPIDEReGAMES"
  - "@SPIFLY"
  - "@THE_CALENDRIER"
  - "@teoconcours"
  - "@timgiveway"
  - "@ToutgagnerCom"
  - "@wayzeeth"
  - "@wsconcours"
  - "@Zarkxlevraii"
  - "@cybervictimes"
  - "@zarkxnft"
  - "@ZetroxEu"
  - "@sim_messier"
  - "@BakoruDeFi"
  - "@YuwyNFT"
  - "@Mr_Rinos"
  - "@corteiz_reps"
  - "@concours_quiz"
  - "@lagamoujeth"
  - "@pormakino"
  - "@WRN2006FRR"
  - "@wrn2006fr"
  - "@AsyaGiveaway"
  - "0xNFTgiveaway"
  - "@cineplus"

# Sentences that the bot will say to act not like a bot
sentence_to_tweet:
  - "The future belongs to those who believe in the beauty of their dreams."
  - "Failure is the foundation of success."
  - "Every day is an opportunity to start over."
  - "Life is a journey, not a destination."
  - "Happiness is a choice."
  - "Patience is a virtue."
  - "Optimism is the key to success."
  - "Mistakes are proof that we are trying."
  - "Perseverance always pays off."
  - "Love is stronger than hate."
  - "Truth always comes from the depths of the soul."
  - "Self-confidence is the key to success."
  - "Perseverance is the mother of success."
  - "Time heals all wounds."
  - "Hope is the antidote to depression."
  - "Creativity is the key to success."
  - "The small pleasures of life are the best."
  - "Friendship is a precious treasure."
  - "Life is what you make of it."
  - "Education is the key to success."
  - "Life is short, enjoy it."
  - "Wisdom comes with age."
  - "Grace is the greatest force of nature."
  - "Beauty is in the eye of the beholder."
  - "Simplicity is the key to life."
  - "Life is a gift, don't waste it."
  - "Compassion is the greatest virtue of man."
  - "Love is the greatest power in the world."
  - "Time is precious, don't waste it."
  - "Curiosity is the engine of discovery."
  - "Hope is the engine of life."
  - "Generosity is the greatest virtue of humanity."
  - "Life is a game, play it to the fullest."
  - "Life is beautiful, appreciate it."
  - "Life is a challenge, rise to it."
  - "Life is a choice, choose it wisely."
  - "Life is a dance, dance it with joy."
  - "Life is a gift, celebrate it."
  - "Life is a miracle, appreciate it."
  - "Tolerance is the key to peace."
  - "Determination is the key to success."
  - "Mutual aid is the key to solidarity."
  - "Life is a unique opportunity, seize it."
  - "Honesty is the basis of a good relationship."
  - "Life is a journey, follow it with courage."
  - "Gratitude is the key to happiness."
  - "Awesome :)"
  - "Let's go!"
  - "Nothing ventured, nothing gained :p"
  - "Let's do it"
  - "Here we go"
  - "We believe in it :o"
  - "I'm trying this contest"
  - "I love gifts :p"
  - "Go go go"
  - "I love it, so I'm trying"
  - "Thanks to you, it's great"
  - "We believe in it!"
  - "Here we go!"
  - "I'm in ^^"
  - "Trying my luck!"
  - "I believe in it to death"
  - "Goooo! :D"
  - "I'm in :)"
  - "Let's try the contest"
  - "May luck be with me"
  - "May luck smile on me :)"
  - "Come on, I believe in it"
  - "Hello, I'm playing, thanks to you"
  - "Come on, it's for me"
  - "Hope keeps us alive"
  - "I comment even if I probably won't win"

# Sentences you need to tweet to invite a friend you must but a space at the end of each sentence
sentence_for_tag:
  - "I invite: "
  - "Thanks! I tag: "
  - "I tag: "
  - "Hop Hop, I invite: "
  - "With me: "
  - "Help me: "
  - "For you guys too: "
  - "Try your luck! "
  - "I'm trying my luck! I hope I win! "
  - "I hope I win! "
  - "Thanks for the contest! Try this too: "
  - "May luck be with me! And you "
  - "Thanks for organizing this contest! It might interest you "
  - "We cross our fingers! You too "
  - "This one's for you! : "
  - "We're winning this one"
  - "I hope I win! We're participating! "
  - "Thanks for organizing this contest! "
  - "Good luck everyone! "
  - "I love contests, and I know you do too "
  - "I really want to win, try it too "
  - "I'm participating, and I invite "
  - "Hello, I participate with pleasure. Thanks for this contest and have a nice day! "
  - "Thank you very much, I love your account. I wish you continued success. I invite "
  - "Hello, I participate with pleasure in this super contest, and I invite "
  - "Superb! I'm trying my luck willingly, and I invite "
  - "Great, I'm participating with pleasure with "
  - "Hello, I'm trying my luck with "
  - "Hello, I'm trying my luck willingly, and I invite "
  - "Thank you very much for this super contest, I tag "
  - "Great! I'm trying my luck, and I identify "
  - "Thanks! I invite "
  - "Hello!!! Thank you very much, I'm trying my luck, thanks and have a nice day! I tag "
  - "Hello, I participate with pleasure for this beautiful gift, and I invite "
  - "Hello and thanks for this super contest :) I invite "
  - "Hello, too nice this contest. Try it too "
  - "I tag my friends "
  - "We're trying again and again "
  - "I'm trying my luck alongside "
  - "Interested? "
  - "What do you think? Come and participate too "
  - "Let's go, I'm sure we'll win this time :) "

# Sentences you need to tweet when you need to do a comment but don't need to invite a friend you must but a space at the end of each sentence
sentence_for_random_comment:
  - "Thanks! "
  - "I'm participating "
  - "Hop Hop "
  - "May the force be with me "
  - "I'm trying my luck! I hope I win! "
  - "I hope I win! "
  - "Thanks for the contest! "
  - "May luck be with me! "
  - "Thanks for organizing this contest! "
  - "We cross our fingers! "
  - "This is for me! "
  - "We're winning this one"
  - "I hope I win! I'm participating! "
  - "Thanks for organizing this contest! "
  - "Good luck everyone! "
  - "I love contests, especially this one "
  - "I really want to win "
  - "Hello, I participate with pleasure. Thanks for this contest and have a nice day! "
  - "Thank you very much, I love your account. I wish you continued success "
  - "Hello, I participate with pleasure in this super contest "
  - "Superb! I'm trying my luck willingly "
  - "Great, I participate with pleasure "
  - "Hello, I'm trying my luck "
  - "Hello, I'm trying my luck willingly "
  - "Thank you very much for this super contest "
  - "Great! I'm trying my luck "
  - "Hello!!! Thank you very much, I'm trying my luck "
  - "Hello, I participate with pleasure for this beautiful gift "
  - "Hello and thanks for this super contest :) "
  - "Hello, too nice this contest. "
  - "We're trying again and again "
  - "I'm trying my luck even if I'm unlikely to win "
  - "Interested? "
  - "Let's go, I'm sure we'll win this time :) "

# Hashtags we don't want to tweet
hashtag_to_blacklist:
  - "giveaway"
  - "contest"
  - "rt"
  - "follow"
  - "giveaways"
  - "game"
  - "games"
  - "gift"
  - "gifts"
  - "competition"
  - "giveway"
  - "tweet"
  - "comment"
  - "followers"
  - "follower"
  - "twitter"
  - "tag"
  - "gamecontest"
  - "giveawayalert"
  - "retweet"
  - "mention"
  - "gift"
  - "free"
  - "christmasgift"
  - "announcement"
  - "christmas"
  - "merrychristmas"

# We don't want to participate in giveaways with these words
giveaway_to_blacklist:
  - "nude"
  - "anal"
  - "sex"
  - "sorare"
  - "freebet"
  - "training"
  - "dvd"
  - "mint"
  - "freemint"
  - "movie"
  - "cinema"
  - "ebook"
  - "gode"
  - "porn"
  - "adult"


# If headless is set to True the bot won't open a chrome windows while doing giveaways otherwise it will
headless: True

#Add your own flux rss those will be used to make tweet after doing giveaway
flux_rss:
  - "https://www.france24.com/fr/rss"
  - "https://www.france24.com/fr/europe/rss"
  - "https://www.france24.com/fr/france/rss"
  - "https://www.france24.com/fr/afrique/rss"
  - "https://www.france24.com/fr/moyen-orient/rss"
  - "https://www.france24.com/fr/am%C3%A9riques/rss"
  - "https://www.france24.com/fr/asie-pacifique/rss"
  - "https://www.france24.com/fr/%C3%A9co-tech/rss"
  - "https://www.france24.com/fr/sports/rss"
  - "https://www.france24.com/fr/culture/rss"
  - "https://www.france24.com/fr/plan%C3%A8te/rss"

# If copy is set to True the bot will copy comment to have way better comment overall
copy: True

#If forever_loop is set to true the bot will run forever otherwise it will run once
forever_loop: False

#The minimum time to wait in second beetween each follow, giveaway done (Like,Retweet,Comment if needed) , random tweet, random retweet the bot will choose a random time beetween min and max time
min_time: 45
#If this option is set to true the bot will make a sleep of 1H30 every 10 giveaways to act more human
human: False

#The maximum time to wait in second beetween each follow, giveaway done (Like,Retweet,Comment if needed) , random tweet, random retweet the bot will choose a random time beetween min and max time
max_time: 300
#If the bot crashed and you want to redo the giveaway you where doing just set the value to true
crash_or_no: False

#If the option is set to False the bot will only @ account withouth the sentence when he need to
add_sentence_to_tag: True

#If random is set to true the bot will do even more random action: It will do a random number of retweet and tweet beetween 1 and random_tweet_nb and random_retweet_nb and it will comment withouth sentence on random time
random_action: False

# If the value is set to true the bot will make random retweet and tweet
random_retweet_and_tweet: True

# If the value is set to true the bot will search and rt random tweet based on word_to_rt list
rt_your_word: False

# Words to be used to retweet a random tweet
word_to_rt:
  - "football"
  - "music"
  - "cinema"

# If these words are in the tweet, the bot won't retweet it
rt_to_blacklist:
  - "jeuxconcours"
  - "contest"


#If the option is set to True the bot will add # to comment other he won't
add_hashtag_to_comment: True

# If the value is set to true the bot will make random retweet and tweet
random_retweet_and_tweet: True

# The number of random tweet to do (to make this work only if your account is new otherwise you can skip it you need to make a tweet and accept twitter circle once and then it will work)
random_tweet_nb: 5

# The number of random retweet to do
random_retweet_nb: 5

# The language of the tweet to search fr,en etc put any if you want to search tweet in any language
tweet_lang: "en"

# Maximum number of giveaway retrieve for each word
max_giveaway: 100

# Minimum of like the tweet must have
minimum_like: 100

# Minimum of reetweet the tweet must have
minimum_rt: 200

#Maximum day for a giveaway to be done
maximum_day: 7

#Number of giveaway the bot can do
nb_of_giveaway: 30
