#Account info write the username of all your account
account_username:
  - "s"

#Account info write the password of all your account
account_password:
  - "S"

# Words to search for giveaway
words_to_search:
  - "#concours"
  - "#JeuConcours"
  - "concours pour gagner"
  - "Gagnez rt + follow"
  - "RT & follow"
  - "rt suivre t.a.s"
  - "concours rt like"
  - "concours rt fav"
  - "RT tweet Follow"
  - "concours rt follow"
  - "rt follow tas"
  - "rt follow tirage au sort"
  - "rt follow t.a.s"
  - "rt follow gagner"
  - "rt follow commente"
  - "rt suivre concours"
  - "rt suivez concours"
  - "rt suivre tirage au sort"
  - "rt suivre tas"
  - "concours remporter"
  - "remporter rt"
  - "concours tas le"
  - "concours résultats le rt"
  - "concours t.a.s le"
  - "tirage au sort concours"
  - "concours résultat le rt"
  
# Accounts we want to invite you must but a space at the end of each account and a space at the	start of the first account
accounts_to_tag:
  - " @cnn "
  - "@BarackObama "
  - "@EmmanuelMacron "

# Accounts that we don't want to follow
accounts_to_blacklist:
  - "@RealB0tSpotter"
  - "@jflessauSpam"
  - "@b0ttem"
  - "@BotSpotterBot"
  - "@gulzaarAvi"
  - "@BotFett"
  - "@ElChap0420"
  - "@RealB0tSpotter"
  - "@YNTF"
  - "@0xCryptax"
  - "@0xHaz666"
  - "@0xMakeMoney"
  - "@AGoldboxDeals"
  - "@BestConcourss"
  - "@BlackPromos"
  - "@BrownConcours"
  - "@buuuffNFT"
  - "@ChrisGeekWorld"
  - "@ConcoursYoko"
  - "@Croissant_NFA"
  - "@cryptogmznft"
  - "@destyy657"
  - "@drakebil22"
  - "@Eks74326603"
  - "@FailsDrole"
  - "@oxyGiveaway"
  - "@GarwyNFT"
  - "@GreyConcours"
  - "@LAGAMINGROOM"
  - "@levraizarkx"
  - "@lofi_feeling"
  - "@MkNFTz"
  - "@MONSIEURCHOUYTB"
  - "@MONSIEURCHOYTB"
  - "@NeyaGiveaway"
  - "@nftconcours"
  - "@simmessier"
  - "@NigmoInft"
  - "@Nigmolnft"
  - "@PolinskiNFT"
  - "@slconcours"
  - "@SPIDEReGAMES"
  - "@SPIFLY"
  - "@THE_CALENDRIER"
  - "@teoconcours"
  - "@timgiveway"
  - "@ToutgagnerCom"
  - "@wayzeeth"
  - "@wsconcours"
  - "@Zarkxlevraii"
  - "@cybervictimes"
  - "@zarkxnft"
  - "@ZetroxEu"
  - "@sim_messier"
  - "@BakoruDeFi"
  - "@YuwyNFT"
  - "@Mr_Rinos"
  - "@corteiz_reps"
  - "@concours_quiz"
  - "@lagamoujeth"
  - "@pormakino"
  - "@WRN2006FRR"
  - "@wrn2006fr"
  - "0xNFTgiveaway"

# Sentences that the bot will say to act not like a bot
setence_to_tweet:
  - "L'avenir appartient à ceux qui croient en la beauté de leurs rêves."
  - "L'échec est la fondation de la réussite."
  - "Chaque jour est une occasion de recommencer."
  - "La vie est un voyage, pas une destination."
  - "Le bonheur est un choix."
  - "La patience est une vertu."
  - "L'optimisme est la clé du succès."
  - "Les erreurs sont la preuve que nous essayons."
  - "La persévérance paie toujours."
  - "L'amour est plus fort que la haine."
  - "La vérité sort toujours du fond de l'âme."
  - "La confiance en soi est la clé de la réussite."
  - "La persévérance est la mère de la réussite."
  - "Le temps guérit toutes les blessures."
  - "L'espoir est l'antidote de la dépression."
  - "La créativité est la clé de la réussite."
  - "Les petits plaisirs de la vie sont les meilleurs."
  - "L'amitié est un trésor précieux."
  - "La vie est ce que vous en faites."
  - "L'éducation est la clé du succès."
  - "La vie est courte, profitez-en."
  - "La sagesse vient avec l'âge."
  - "La grâce est la plus grande force de la nature."
  - "La beauté est dans les yeux de celui qui regarde."
  - "La simplicité est la clé de la vie."
  - "La vie est un cadeau, ne le gaspillez pas."
  - "La compassion est la plus grande vertu de l'homme."
  - "L'amour est le plus grand pouvoir du monde."
  - "Le temps est précieux, ne le gaspillez pas."
  - "La curiosité est le moteur de la découverte."
  - "L'espoir est le moteur de la vie."
  - "La générosité est la plus grande vertu de l'humanité."
  - "La vie est un jeu, jouez-le à fond."
  - "La vie est belle, appréciez-la."
  - "La vie est un défi, relevez-le."
  - "La vie est un choix, choisissez-la avec sagesse."
  - "La vie est une danse, dansez-la avec joie."
  - "La vie est un don, soyez reconnaissant."
  - "La vie est une aventure, soyez audacieux."
  - "La vie est un voyage, profitez-en."
  - "La vie est un roman, écrivez-le avec passion."
  - "La vie est un cadeau, célébrez-la."
  - "La vie est un miracle, appréciez"
  - "La tolérance est la clé de la paix."
  - "La détermination est la clé de la réussite."
  - "L'entraide est la clé de la solidarité."
  - "La vie est une occasion unique, saisissez-la."
  - "L'honnêteté est la base d'une bonne relation."
  - "La vie est un chemin, suivez-le avec courage."
  - "La gratitude est la clé du bonheur."
  - "Génial :)"
  - "c'est parti !"
  - "qui ne tente rien n'a rien :p"
  - "Allez zou"
  - "Here we go"
  - "On y croit :o"
  - "Je tente ce concour"
  - "j'adore les cadeaux :p"
  - "go go go"
  - "je kiffe donc je tente"
  - "Merci à vous, c'est top"
  - "On y croit !"
  - "zoouu !"
  - "je joue ^^"
  - "Je tente on sait jamais !"
  - "j'y crois à mort"
  - "goooo ! :D"
  - "Je joue :)"
  - "allez je tente le concours"
  - "Que la chance soit avec moi"
  - "Que la chance me sourit :)"
  - "Allez là, j'y crois"
  - "hello, je joue, merci à vous"
  - "Allez c'est pour moi"
  - "l'espoir fait vivre"
  - "je commente même si je fais surement pas gagner"

# Sentences you need to tweet to invite a friend you must but a space at the end of each sentence
sentence_for_tag:
  - "J'invite : "
  - "Merci ! je tag : "
  - "Je tag : "
  - "Hop Hop, j'invite : "
  - "Avec moi : "
  - "Help me : "
  - "Pour vous aussi les gars : "
  - "tentez votre chance ! "
  - "Je tente ma chance ! J'espère que je vais gagner ! "
  - "J'espère que vais gagner ! "
  - "Merci pour le concours ! Essayez aussi : "
  - "Que la chance soit avec moi ! et vous "
  - "Merci d'organiser ce concours ! Ça peut vous intéresser "
  - "On croise les doigts ! vous aussi "
  - "C'est pour vous ça ! : "
  - "Celui là on le gagne"
  - "J'espère que vais gagner ! On participe ! "
  - "Merci d'organiser ce concours ! "
  - "Bonne chance à tous ! "
  - "J'adore les concours et je sais que vous aussi "
  - "J'ai tellement envie de gagner, essayez vous aussi "
  - "Je participe et j'invite "
  - "Bonjour je participe avec plaisir. Merci pour ce concours et bonne journée ! "
  - "Merci beaucoup j'adore votre compte. Je vous souhaite une belle continuation. J'invite "
  - "Bonjour je participe avec plaisir à ce super concours et j'invite "
  - "Superbe ! Je tente ma chance bien volontiers et j'invite "
  - "Chouette bonjour je participe avec plaisir avec "
  - "Bonjour je tente ma chance avec "
  - "Bonjour, Je tente ma chance bien volontiers et j'invite "
  - "Merci beaucoup pour ce super concours, je tague "
  - "Bonjour génial ! Je tente ma chance et j'identifie "
  - "Merci ! J'invite "
  - "Hello !!! Merci beaucoup je tente ma chance merci et bonne journée ! Je tague "
  - "Bonjour je participe avec plaisir pour ce beau cadeau et j'invite "
  - "Bonjour et merci pour ce super concours :) j'invite "
  - "Bonjour, trop Sympa ce concours. Essayez-vous aussi "
  - "Je tag mes amis "
  - "On tente encore et encore "
  - "Je tente ma chance aux côtés de "
  - "Ça vous intéressent ? "
  - "Qu'est ce que vous en pensez ? Allez participez-vous aussi "
  - "Let's go, je suis sûr qu'on va gagner cette fois :) "

# Sentences you need to tweet when you need to do a comment but don't need to invite friend you must but a space at the end of each sentence
sentence_for_random_comment:
  - "Merci ! "
  - "Je participe "
  - "Hop Hop "
  - "Que la force soit avec moi "
  - "Je tente ma chance ! J'espère que je vais gagner ! "
  - "J'espère que vais gagner ! "
  - "Merci pour le concours ! "
  - "Que la chance soit avec moi ! "
  - "Merci d'organiser ce concours ! "
  - "On croise les doigts ! "
  - "C'est pour moi ça ! "
  - "Celui là on le gagne"
  - "J'espère que vais gagner ! Je participe ! "
  - "Merci d'organiser ce concours ! "
  - "Bonne chance à tous ! "
  - "J'adore les concours et surtout celui si "
  - "J'ai tellement envie de gagner "
  - "Bonjour je participe avec plaisir. Merci pour ce concours et bonne journée ! "
  - "Merci beaucoup pour j'adore votre compte. Je vous souhaite une belle continuation "
  - "Bonjour je participe avec plaisir à ce super concours "
  - "Superbe ! Je tente ma chance bien volontiers "
  - "Chouette bonjour je participe avec plaisir "
  - "Bonjour je tente ma chance "
  - "Bonjour, Je tente ma chance bien volontiers "
  - "Merci beaucoup pour ce super concour "
  - "Bonjour génial ! Je tente ma chance "
  - "Hello !!! Merci beaucoup je tente ma chance "
  - "Bonjour je participe avec plaisir pour ce beau cadeau "
  - "Bonjour et merci pour ce super concours :) "
  - "Bonjour, trop Sympa ce concours. "
  - "On tente encore et encore "
  - "Je tente ma chance même si je risque de ne pas gagner "
  - "Ça vous intéressent ? "
  - "Let's go, je suis sûr qu'on va gagner cette fois :) "

# hashtag we don't want to tweet
hashtag_to_blacklist:
  - "giveaway"
  - "concours"
  - "rt"
  - "follow"
  - "jeuconcours"
  - "jeu"
  - "jeux"
  - "cadeau"
  - "cadeaux"
  - "concour"
  - "giveway"
  - "tweet"
  - "commente"
  - "followers"
  - "follower"
  - "twitter"
  - "tag"
  - "jeuxconcours"
  - "giveawayalert"
  - "retweet"
  - "mentionne"
  - "kdo"
  - "gratuit"
  - "cadeaunoel"
  - "annonce"
  - "noel"
  - "joyeuxnoel"

# We don't want to participate in giveaway with these words
giveaway_to_blacklist:
  - "nude"
  - "sorare"
  - "freebet"

#If forever_loop is set to true the bot will run forever otherwise it will run once
forever_loop: True

#The minimum time to wait in second beetween each follow, giveaway done (Like,Retweet,Comment if needed) , random tweet, random retweet the bot will choose a random time beetween min and max time
min_time: 45

#The maximum time to wait in second beetween each follow, giveaway done (Like,Retweet,Comment if needed) , random tweet, random retweet the bot will choose a random time beetween min and max time
max_time: 400

#If the bot crashed and you want to redo the giveaway you where doing just set the value to true
crash_or_no: False

# If the value is set to true the bot will make random retweet and tweet
random_retweet_and_tweet: True

# The number of random tweet to do (to make this work only if your account is new otherwise you can skip it you need to make a tweet and accept twitter circle once and then it will work) 
random_tweet_nb: 5

# The number of random retweet to do
random_retweet_nb: 5

# Maximum number of giveaway retrieve for each word
max_giveaway: 50

# Minimum of like the tweet must have
minimum_like: 10

# Minimum of reetweet the tweet must have
minimum_rt: 200

#Maximum day for a giveaway to be done
maximum_day: 10

#Number of giveaway the bot can do
nb_of_giveaway: 3