#Write 1 if you only have one account and write two if you have several account
main_mode:
  - 1

#Account info write the username of all your account
account_username:
  - "ut"
  
#Account info write the password of all your account
account_password:
  - "S1"
  
# Words to search for giveaway
words_to_search:
  - "#concours"
  - "#JeuConcours"
  - "concours pour gagner"
  - "Gagnez rt + follow"
  - "RT & follow"
  - "rt suivre t.a.s"
  - "concours rt like"
  - "concours rt fav"
  - "RT tweet Follow"
  - "concours rt follow"
  - "rt follow tas"
  - "rt follow tirage au sort"
  - "rt follow t.a.s"
  - "rt follow gagner"
  - "rt follow commente"
  - "rt suivre concours"
  - "rt suivez concours"
  - "rt suivre tirage au sort"
  - "rt suivre tas"

# Accounts we want to invite you must but a space at the end of each account
accounts_to_tag:
  - "@Mediavenir "
  - "@NetflixFR "
  - "@ActuFoot_ "

# Accounts that we don't want to follow
accounts_to_blacklist:
  - "@RealB0tSpotter"
  - "@jflessauSpam"
  - "@b0ttem"
  - "@BotSpotterBot"
  - "@gulzaarAvi"
  - "@BotFett"

# Sentences you need to tweet to invite a friend you must but a space at the end of each sentence
sentence_for_tag:
  - "J'invite : "
  - "Merci ! je tag : "
  - "Je tag : "
  - "Hop Hop, j'invite : "
  - "Avec moi : "
  - "Help me : "
  - "Pour vous aussi les gars : "
  - "tentez votre chance ! "
  - "Je tente ma chance ! J'espère que je vais gagner ! "
  - "J'espère que vais gagner ! "
  - "Merci pour le concours ! Essayez aussi : "
  - "Que la chance soit avec moi ! et vous "
  - "Merci d'organiser ce concours ! Ça peut vous intéresser "
  - "On croise les doigts ! vous aussi "
  - "C'est pour vous ça ! : "
  - "Celui là on le gagne"
  - "J'espère que vais gagner ! On participe ! "
  - "Merci d'organiser ce concours ! "
  - "Bonne chance à tous ! "
  - "J'adore les concours et je sais que vous aussi "
  - "J'ai tellement envie de gagner, essayez vous aussi "
  - "Je participe et j'invite "
  - "Bonjour je participe avec plaisir. Merci pour ce concours et bonne journée ! "
  - "Merci beaucoup j'adore votre compte. Je vous souhaite une belle continuation. J'invite "
  - "Bonjour je participe avec plaisir à ce super concours et j'invite "
  - "Superbe ! Je tente ma chance bien volontiers et j'invite "
  - "Chouette bonjour je participe avec plaisir avec "
  - "Bonjour je tente ma chance avec "
  - "Bonjour, Je tente ma chance bien volontiers et j'invite "
  - "Merci beaucoup pour ce super concours, je tague "
  - "Bonjour génial ! Je tente ma chance et j'identifie "
  - "Merci ! J'invite "
  - "Hello !!! Merci beaucoup je tente ma chance merci et bonne journée ! Je tague "
  - "Bonjour je participe avec plaisir pour ce beau cadeau et j'invite "
  - "Bonjour et merci pour ce super concours :) j'invite "
  - "Bonjour, trop Sympa ce concours. Essayez-vous aussi "
  - "Je tag mes amis "
  - "On tente encore et encore "
  - "Je tente ma chance aux côtés de "
  - "Ça vous intéressent ? "
  - "Qu'est ce que vous en pensez ? Allez participez-vous aussi "
  - "Let's go, je suis sûr qu'on va gagner cette fois :) "

# hashtag we don't want to tweet
hashtag_to_blacklist:
  - "giveaway"
  - "concours"
  - "rt"
  - "follow"
  - "jeuconcours"
  - "jeu"
  - "jeux"
  - "cadeau"
  - "cadeaux"
  - "concour"
  - "giveway"
  - "tweet"
  - "commente"
  - "followers"
  - "follower"
  - "twitter"
  - "tag"
  - "jeuxconcours"
  - "giveawayalert"
  - "retweet"
  - "mentionne"
  - "kdo"
  - "gratuit"
  - "cadeaunoel"
  - "annonce"
  - "noel"
  - "joyeuxnoel"

# We don't want to participate in giveaway with these words
giveaway_to_blacklist:
  - "nude"
  - "sorare"

# Maximum number of giveaway retrieve for each word
max_giveaway : 10

# Minimum of like the tweet must have
minimum_like : 10

# Minimum of reetweet the tweet must have
minimum_rt : 20

#Maximum day for a giveaway to be done
maximum_day: 30
